### ISSUE TITLE
np.bool deprecated

### ISSUE THREAD

**Issue by teuben** [GBTSpectroscopy/degas#157]
modern numpy has deprecated np.bool/int/float.   For GBT--EDGE i have a branch testing the new bool/int/float, which seems to work.  Should become a pull request soon.

**Comment by low-sky** [comment]
I also patched this today.  I’ll merge tomorrow morning!  There are a couple places to keep the bit depth set using the numpy data types.

**Comment by teuben** [comment]
ah, what a "terrible" coincidence.   I'm pretty fed up with the python ecosystem. I could only find one python from anaconda3 that made a fresh build of pipeline work.

**Comment by low-sky** [comment]
Addressed in #158
