### ISSUE TITLE
Re-define ON/OFF sections of the scans

### ISSUE THREAD

**Issue by low-sky** [GBTSpectroscopy/degas#39]
Since our scans are short, galactic emission could appear at the beginning of the scans.  We need to define the ON/OFF based on RA/Dec offset from the galaxy and define a "zone of exclusion" around the galaxy.

**Comment by aakepley** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/paVF8ZTL/73-test)

**Comment by low-sky** [comment]
Addressed in gbtpipe with new OFF options and 70e4ace
