### ISSUE TITLE
New issue for reading the weather information?

### ISSUE THREAD

**Issue by JialLi** [GBTSpectroscopy/degas#62]
Hi --

When I returned back to the calculating OFF spectrum part I met an error for the first time: 
"Permission denied: 'users/rmaddale/Weather/ArchiveCoeffs/CoeffsTatmFreqList_avrg_57754_58119.txt". I went to the folder and found that indeed I had no right to read it.

Therefore at this moment, I cannot run the 'calscan'. I am wondering whether the access has been changed recently?

**Comment by aakepley** [comment]
Hmm... it appears to be just that one file. I'm going to email Ron and see if he knows what's going on. I have a copy of the weather data on disk locallly, so I will tar it up and send to you by email. You can use the copy of the weather data in the reduction if you follow the instructions for setting up an environment variable pointing to your local weather install here: https://github.com/GBTSpectroscopy/degas#local-installation-of-the-degas-pipeline

**Comment by JialLi** [comment]
Ron has fixed the problem now!
