### ISSUE TITLE
add hook to apply eta_mb value and convert calibrated scans to Tmb

### ISSUE THREAD

**Issue by aakepley** [GBTSpectroscopy/degas#78]
We are adopting one value per frequency setup (HCN/HCO+, 13CO/C18O, 12CO) for all feeds.

Amanda will provide nominal values based on her planetary observations this afternoon (need to find the relevant file).

**Comment by aakepley** [comment]
Do this in the clean split step? Or after? 

I think I might be able to write something that works.

**Comment by low-sky** [comment]
done by @aakepley
